/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/holo-desk-8d627619a2404cd0bc6fef06bea0e870
Title: Holo Desk
*/

import  { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HelloDesk = (props) =>{
    const { nodes, materials } = useGLTF('/models/hello-desk.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-26.244, -3.694, 69.055]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={[1.737, 0.586, 0.586]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.MaterialFBXASC032FBXASC0352142150880.geometry}
                            material={materials.MaterialFBXASC032FBXASC0352142150880}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.MaterialFBXASC032FBXASC0352142146756.geometry}
                            material={materials.MaterialFBXASC032FBXASC0352142146756}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MaterialFBXASC032FBXASC0352142148090.geometry}
                        material={materials.MaterialFBXASC032FBXASC0352142148090}
                        position={[-25.864, 2.807, 70.363]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={[1.737, 0.586, 7.935]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/hello-desk.glb')
export default HelloDesk;
